<div>
    <div>
        <h1>Terms Of Use <small>Effective March 1, 2016</small></h1>
    </div>
</div>
<h3>Use of the Services</h3>
<p>You are responsible for your use of the Services, for any information you choose to make available, for any transactions you participate in and for any consequences thereof.</p>
<p>You may use the Services only if you are of legal age and have the capacity to form a binding contract and are not a person barred from receiving services under the laws of the United States or other applicable jurisdiction. You may use the Services only in compliance with these Terms and all applicable local, state, national, and international laws, rules and regulations.</p>
<p>The Services that Eoction provides are always evolving and the form and nature of the Services that Eoction provides may change from time to time without prior notice to you. In addition, Eoction may need to stop (permanently or temporarily) providing the Services (or any features within the Services) to you or to users generally if we determine it necessary and may not be able to provide you with prior notice.</p>
<p>In order to use certain Services, you will need to register with Eoction, create a username and provide certain information about yourself as prompted by the registration form, including a valid email address. You may not use a username for the purpose of impersonating another person or entity, including staff or any other representative of Eoction. We reserve the right to remove or reclaim inactive usernames or usernames on behalf of businesses or individuals that hold trademark or other legal claim on those usernames. By creating an account, you agree to abide by these Terms and provide accurate information. Unless you are an agent authorized to bind another person and you are acting under their direction, you may not create an account for anyone other than yourself. We reserve the right to suspend or terminate your account if any information provided proves to be inaccurate, false, or otherwise in violation of these Terms.</p>
<h3>Passwords</h3>
<p>You are responsible for safeguarding the password that you use to access the Services. You agree to take sole responsibility for any activities or actions under your account, whether or not you have authorized such activities or actions. We encourage you to use strong passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) with your account. You must immediately notify Eoction of any unauthorized use of your account, or if you have reason to believe that your password was lost, stolen, disclosed to an unauthorized third party, or otherwise may have been compromised. Eoction is not liable for any loss or damage arising from your failure to comply with the above requirements.</p>
<h3>Selling</h3>
<p>If you use the Services to sell items, you agree to abide by Seller Rules ("Seller Rules"), which are hereby incorporated by reference. These rules are detailed in the Eoction <a href="https://eoction.com/#">help section</a> and are subject to change. In the event of any conflict between the text in these Terms and Conditions and the Seller Rules, the Seller Rules will govern.You agree to pay Eoction's fees, to assume full responsibility for the content of your listing and your items offered for sale. You agree to display information accurately about your listings, to ship items purchased by buyers promptly after payment, to provide a valid credit card or verified PayPal address, to adhere to all listing rules and restrictions and to respond to enquiries from Eoction in a timely manner. You will not list any items that are prohibited by law or are otherwise prohibited by our Seller Rules. You are solely responsible for the collection and payment of any and all applicable taxes, levies, or other applicable fees associated with your sales of items. Most Eoction auctions have no reserve prices, so your opening bid setting represents a binding offer to sell your item at that opening bid or any higher amount. You will not to engage with any bidders in manipulative, or deceptive bidding, including shill bidding, as described in the Eoction <a href="https://eoction.com/#">help section</a>. You will not to transfer your Eoction account, including feedback and your user ID, to any other party without our consent.</p>
<p>Eoction uses third parties to process payments and to payout funds to sellers. Eoction uses Braintree, a division of PayPal, Inc. (Braintree) for payment processing. In order for you to use Braintree's payment processing services, you must enter into the Merchant Services Agreement (MSA) with Braintree and its sponsoring bank. The MSA is available <a href="http://www.braintreepayments.com/agreements/merchant">here</a>. By accepting this Agreement, you agree: (a) that you have downloaded or printed the MSA, and (b) that you have reviewed and agree to the MSA. Please note that Eoction is not a party to the MSA and that you, Braintree and Braintree's sponsoring bank are the three parties to the MSA and that Eoction has no obligations or liability to you under the MSA. If you have questions regarding the MSA, please contact Braintree at 877.434.2894. You expressly authorize Eoction's service provider, Dwolla, Inc. to originate credit transfers to your financial institution account.</p>
<p>These requirements represent a subset of the full Seller Rules, which are described in detail on the Eoction <a href="https://eoction.com/#">help section</a> and in the Services. If you do not agree to these Seller Rules, do not list items for sale. Failure to comply with any of the Seller Rules may result in your account being suspended or banned from participating in the Services.</p>
<h3>Bidding &amp; Buying</h3>
<p>If you use the Services to bid on or buy items, you agree to pay for the items purchased within a timely manner. Eoction auctions are real, and any bids placed are binding offers to purchase the item on the block. A full set of buyer questions and answers is available in the Eoction <a href="https://eoction.com/#">help section</a>.</p>
<p>You will not engage in any manipulative or disruptive bidding practices, including without limitation "shill" bidding or any other practice designed to interfere with the natural progression of bidding or otherwise affect ultimate sale price of any item.</p>
<p>When you win an item on Eoction, you are purchasing directly from the seller of the item, not from Eoction. Any details regarding the item, including but not limited to product descriptions, warranties offered, refund policies or any other terms are between you and the seller. You should review and familiarize yourself with any and all terms of sale provided by the seller prior to bidding on an item.</p>
<p>Eoction does not have any control over or liability for the quality, safety, legality, descriptions, photos, or other aspect of the items listed for sale, nor does Eoction have any control over or liability for the accuracy, truthfulness, quality, or other aspect of the materials and information associated with listings. Eoction is not liable or responsible for defective items. If an item sold on Eoction is delivered to you in a defective condition, your sole remedy is directly with the seller.</p>
<p>Without limiting the foregoing, Eoction reserves the right in its sole discretion to resolve disputes between buyers and sellers. You agree that Eoction has the right to make the final decision in any dispute where Eoction chooses to intervene. If we resolve a dispute in the buyer&rsquo;s favor, we may refund the buyer&rsquo;s payment up to the full cost of the item in dispute, including shipping, and may require the seller to reimburse us for the full amount refunded. Eoction further reserves the right to correct any mistakes in payments to buyers or sellers, including any processing errors we discover, by debiting or crediting the payment method used in the applicable transaction.</p>
<h3>Fees</h3>
<p>We charge fees for using some services. When you use a service that has a fee, you have an opportunity to review and accept the fees that you will be charged based on our Fees schedule, which we may change from time to time. Unless otherwise stated, all fees are quoted in U.S. Dollars. You are responsible for paying all fees and applicable taxes in a timely manner with a valid payment method. If your payment method fails or your account is past due, we may, in our sole discretion, suspend your account and/or collect fees owed using any and all legal collection mechanisms.</p>
<h3>Feedback</h3>
<p>Users may submit feedback information regarding sellers and buyers that use the Services. You may only use the rating and feedback features for the bona-fide purpose of submitting feedback regarding the experience you had. Any other use of the feedback system is prohibited. You may not threaten to submit negative feedback or withhold positive feedback in order to receive benefits beyond those to which you are entitled and you may not submit feedback for the purpose of manipulating another user&rsquo;s rating. Feedback information submitted by a user may be made available through the Services to other users.</p>
<h3>Privacy</h3>
<p>Any personal information that you provide to us is subject to our Privacy Policy, which governs our collection and use of your personal information. You understand that by using the Services you consent to the collection and use (as set forth in the Privacy Policy) of this information, including the transfer of this information to the United States and/or other countries for storage, processing and use by Eoction. As part of providing you the Services, we may need to provide you with certain communications, such as service announcements and administrative messages. These communications are considered part of the Services and your Eoction account and you cannot opt out of receiving them without terminating your account after all pending transactions have been completed.</p>
<h3>Content</h3>
<p>The content you make available, post, or display will be viewable by other users of the Services. You should only make available information or provide Content that you are comfortable sharing with others under these Terms.</p>
<p>All Content is the sole responsibility of the person who originated such Content, including its legality, reliability, and appropriateness. We do not monitor or control the Content posted via the Services, and we cannot take responsibility for such Content. Any use of or reliance on any Content or materials posted via the Services or obtained by you through the Services is at your own risk.</p>
<p>We do not endorse, support, represent or guarantee the completeness, truthfulness, accuracy, or reliability of any Content or communications posted via the Services. You understand that by using the Services, you may be exposed to Content that might be offensive, harmful, inaccurate or otherwise inappropriate, or in some cases, postings that have been mislabeled or are otherwise deceptive. Under no circumstances will Eoction be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available via the Services or broadcast elsewhere.</p>
<p>Eoction may offer a catalog of items, which may include photos, descriptions, and other information provided by third parties. Eoction cannot guarantee that the information contained in such catalog will be accurate or up to date, and you agree not to hold such third party Content providers, or Eoction, responsible for any inaccuracies.</p>
<h3>Content You Submit</h3>
<p>Any Content you provide must comply with the Seller Rules, as described in the <a href="https://eoction.com/#">help section</a> (which are hereby incorporated by reference and are part of these Terms and describe what content is prohibited on the Services). You are responsible for your use of the Services, for any Content you provide, and for any consequences thereof, including the use of your Content by other users and our third party partners. Eoction is not responsible or liable for any use of your Content by Eoction in accordance with these Terms. You represent and warrant that (i) you have all the rights, power and authority necessary (you own it or have the right to use it) to grant the rights granted herein to any Content submitted; and (ii) the posting of such Content on or through the Service does not violate any privacy rights, publicity rights, copyrights, contract rights, or any other rights of any person or entity.</p>
<p>You may request removal of your Content from the Services at any time by specifically deleting it or sending a request to customer support. Some Content cannot be deleted entirely as it may be needed for tax or other purposes by either Eoction or another user. If you choose to remove your Content or cancel your account, your Content will be removed from public viewing as soon as is practical, (although back-up copies may survive for archival and record keeping purposes), provided, however, in certain instances, copies of your Content may continue to exist in published or recorded form when it has been retransmitted, redistributed, or otherwise. We are not responsible or liable for the removal or deletion of (or the failure to remove or delete) any Content on the Services. We retain the right to create limits on use and storage at our sole discretion at any time with or without notice.</p>
<p>By submitting, posting or displaying Content on or through the Services, you grant us and our third-party service providers and partners a worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute such Content in any and all media or distribution methods (now known or later developed). You agree that this license includes the right for us to make such Content available to other users of the Services, who may also use your Content subject to these Terms to take advantage of the Services. No compensation will be paid with respect to the Content that you submit, post, transmit or otherwise make available through the Services, even if used by other companies, organizations or individuals who partner with Eoction.</p>
<p>We may need to modify or adapt your Content in order to transmit, display or distribute it over computer networks and in various media and/or make changes to your Content as are necessary to conform and adapt that Content to any requirements or limitations of any networks, devices, services or media.</p>
<p>Eoction claims no ownership of any Content submitted, posted or displayed by you on or through the Services. You retain any and all of your rights to any Content you submit, post or display on or through the Services, subject to the exceptions noted herein, and you are solely responsible for protecting those rights.</p>
<h3>Eoction Ownership Rights</h3>
<p>All right, title, and interest in and to the Services (excluding your Content), including all associated intellectual property rights, are and will remain the exclusive property of Eoction and its licensors. The Services are protected by copyright, trademark, and other laws of both the United States and foreign countries. Nothing in the Terms gives you a right to use the Eoction name or any of the Eoction trademarks, logos, domain names, or other distinctive brand features. You may use the Eoction name or any of the Eoction trademarks, logos, domain names, or other distinctive brand features only in the event Eoction grants you the right to do so in a separate written agreement. You shall not sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit, create derivative works from, or otherwise exploit any Content or third party submissions or other proprietary rights not owned by you, (i) without the consent of the respective owners or other valid right, and (ii) in any way that violates the rights of Eoction or any third party. You may not remove, alter, or obscure any copyright, trademark, service mark, or other proprietary rights notices incorporated in or accompanying the Services, including any Content. Any feedback, comments, or suggestions you may provide regarding Eoction or the Services are entirely voluntary and are the sole and exclusive property of Eoction. You hereby irrevocably assign to us all of your right, title and interest in and to such feedback, comments or suggestions, and Eoction is free to use them as we see fit and without any obligation to you.</p>
<h3>Restrictions on Content and Use of the Services</h3>
<p>We reserve the right at all times (but are not obligated to) to remove or refuse to distribute any Content on the Services, which violates these Terms or the Eoction Rules for using the Service and submitting Content. We also reserve the right to access, read, preserve, and disclose any information as we reasonably believe is necessary to (i) satisfy any applicable law, regulation, legal process or governmental request, (ii) enforce the Terms, including investigation of potential violations hereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect the rights, property or safety of Eoction, its users and the public.</p>
<p>Unless you have been specifically permitted to do so in a separate written agreement with Eoction and except as expressly permitted in these Terms, you may not reproduce, modify or prepare derivative works based upon, distribute, sell, transfer, publicly display, publicly perform, transmit, or otherwise use the Content or Services. You may not copy, modify, decompile, reverse-engineer, or disassemble the code used to generate web pages on the Services. You may not harvest usernames, addresses, email addresses, or other personal information for any purpose.</p>
<p>You may not do any of the following while accessing or using the Services: (i) access, tamper with, or use non-public areas of the Services, Eoction's computer systems, or the technical delivery systems of Eoction's providers; (ii) probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures; (iii) access or search or attempt to access or search the Services by any means (automated or otherwise) other than through our currently available, published interfaces that are provided by Eoction (and only pursuant to those terms and conditions), unless you have been specifically allowed to do so in a separate agreement with Eoction; (iv) forge any TCP/IP packet header or any part of the header information in any email or posting, or in any way use the Services to send altered, deceptive or false source-identifying information; or (v) interfere with, or disrupt, (or attempt to do so), the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, mail-bombing the Services, or by scripting the creation of Content in such a manner as to interfere with or create an undue burden on the Services.</p>
<h3>Copyright Policy</h3>
<p>It is the policy of Eoction to terminate your access to the Services if you infringe the copyright rights of others upon receipt of proper notification to Eoction by the copyright owner or the copyright owner's legal agent. Without limiting the foregoing, if you believe that your work has been copied and posted on the Services in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: (i) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (ii) a description of the copyrighted work that you claim has been infringed; (iii) a description of where the material that you claim is infringing is located on the Services; (iv) your address, telephone number, and email address; (v) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; (vi) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. You may contact our Copyright Agent <a href="https://Eoction.com/support/new">here</a>.</p>
<h3>Termination</h3>
<p>If you violate the letter or spirit of any of these Terms, or otherwise create risk or possible legal exposure for us, we reserve the right to suspend or terminate your access to and use of the Services.</p>
<h3>The Services are Available "AS-IS"</h3>
<p>Your access to and use of the Services or any Content is at your own risk. You understand and agree that the Services are provided to you on an "AS IS" and "AS AVAILABLE" basis. Without limiting the foregoing, Eoction DISCLAIMS ANY WARRANTIES, EXPRESS OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF ANY COURSE OF DEALING OR USAGE OF TRADE. We make no warranty and disclaim all responsibility and liability for the completeness, accuracy, availability, timeliness, security or reliability of the Services or any content thereon. We make no guarantee as to the duration or manner in which your items appear on Eoction, whether in our catalog, at auction, or otherwise. Eoction is not responsible or liable for any harm to your computer system, loss of data, glitches, bugs, errors, delays, disruptions, or other harm that results from your access to or use of, inability to access or use, the Services, or any Content. You agree that Eoction is not liable for any damage or losses resulting directly or indirectly from any suspension of your account. We make no warranty that the Services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. No advice or information, whether oral or written, obtained from Eoction or through the Services, will create any warranty not expressly made herein.</p>
<h3>Links</h3>
<p>The Services may contain links to third-party websites or resources. You acknowledge and agree that we are not responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such third party content, goods, or services, including but not limited to: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, legality, appropriateness, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by Eoction of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources. You acknowledge that your use of any third-party websites or resources is governed by that party&rsquo;s terms and privacy policy.</p>
<h3>Indemnity</h3>
<p>You agree to defend, indemnify, and hold harmless Eoction and its partners, and their officers, directors, employees and agents, from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with your access to or use of the Services, your violation of these Terms or any Content posted, published, transmitted or otherwise provided by you or on your behalf.</p>
<h3>Limitation of Liability</h3>
<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, Eoction AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS ARE NOT LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (i) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES; (ii) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES, INCLUDING WITHOUT LIMITATION, ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF OTHER USERS OR THIRD PARTIES; (iii) ANY CONTENT OBTAINED FROM THE SERVICES; OR (iv) UNAUTHORIZED ACCESS, USE OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER LEGAL THEORY, WHETHER OR NOT Eoction HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. UNDER NO CIRCUMSTANCES WILL Eoction&rsquo;S TOTAL LIABILITY TO YOU FROM ALL CAUSES OF ACTION AND UNDER ALL THEORIES OF LIABILITY EXCEED THE AMOUNT YOU PAID Eoction FOR THE USE OF THE SERVICES DURING THE TWELVE MONTHS PRIOR TO THE ACTION GIVING RISE TO THE LIABILITY, IF YOU HAVE MADE ANY PAYMENTS TO Eoction, OR $50 IF YOU HAVE NOT MADE ANY PAYMENTS TO Eoction.</p>
<h3>Exclusions</h3>
<p>Some jurisdictions do not allow the exclusion of certain warranties or the exclusion or limitation of liability for consequential or incidental damages, so the limitations above may not apply to you.</p>
<h3>Waiver &amp; Severability</h3>
<p>The failure of Eoction to enforce any right or provision of these Terms does not constitute a waiver of such right or provision. In the event that any provision of these Terms is held to be invalid or unenforceable, the remaining provisions of these Terms will remain in full force and effect.</p>
<h3>Controlling Law &amp; Jurisdiction</h3>
<p>These Terms and any action related thereto are governed by the laws of the State of California, without regard to or application of its conflict of law provisions or your state or country of residence. All claims, legal proceedings or litigation arising in connection with the Services will be brought solely in San Francisco County, California, and you consent to the jurisdiction of and venue in such courts and waive any objection as to inconvenient forum.</p>
<h3>Entire Agreement</h3>
<p>These Terms, the Eoction Rules and our Privacy Policy are the entire and exclusive agreement between Eoction and you regarding the Services, and these Terms supersede and replace any prior agreements between Eoction and you regarding the Services.</p>
<p>We may revise these Terms from time to time. If we make any material changes to these Terms, we will notify you of such changes by posting them on the Eoction website or by sending you an email or other notification, and we will indicate when such changes will become effective. By continuing to access or use the Services after those revisions become effective, you agree to be bound by the revised Terms.</p>
<p>If you are a California resident, in accordance with Cal. Civ. Code &sect;1789.3, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by contacting them in writing at 1625 North Market Blvd., Suite N 112, Sacramento, CA 95834, or by telephone at 800-952-5210.</p>
<p>These Services are operated and provided by Eoction Inc., 292 Lambert Ave, Palo Alto, CA 94306. If you have any questions about these Terms, please <a href="https://Eoction.com/support/new">contact customer support</a>.</p>